complexity:
  LongMethod:
    threshold: 50
  LargeClass:
    threshold: 800

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  MatchingDeclarationName:
    active: false

style:
  MagicNumber:
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreEnums: true
    ignoreRanges: true
  MaxLineLength:
    maxLineLength: 120
  UnusedPrivateProperty:
    active: true
